ECSWorld          = require "src/ECS/ECSWorld"
Entity            = require "src/ECS/Entity/Entity"
SpriteRenderer    = require "src/ECS/Systems/SpriteRenderer"
RectangleDrawer   = require "src/ECS/Systems/RectangleDrawer"
BasicComponents   = require "src/ECS/Components/BasicComponents"